[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "memvid-mcp-server"
version = "0.2.1"
description = "An MCP server to expose Memvid functionalities to AI clients"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["mcp", "memvid", "video", "memory", "ai"]
authors = [
  {name = "AI Workspace"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "anthropic>=0.57.1",
  "google-genai>=1.24.0",
  "google-generativeai>=0.8.5",
  "mcp[cli]>=1.10.1",
  "memvid",
  "openai>=1.93.0",
  "pypdf2",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-asyncio>=0.21.0",
  "black>=23.0.0",
  "ruff>=0.1.0",
  "mypy>=1.0.0",
]

[project.urls]
Repository = "https://github.com/angrysky56/memvid-mcp-server"
Issues = "https://github.com/angrysky56/memvid-mcp-server/issues"

[project.scripts]
memvid-mcp-server = "memvid_mcp_server.main:main"

[tool.hatch.version]
path = "memvid_mcp_server/__about__.py"

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I001"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
